### ISSUE TITLE
Unicode 15 support

### ISSUE THREAD

**Issue by ThatOneCalculator** [jdecked/twemoji-parser#3]
Support for Unicode 15.0.0 for https://github.com/jdecked/twemoji/pull/43

**Comment by ThatOneCalculator** [comment]
Can this be published as an NPM release?

**Comment by ThatOneCalculator** [comment]
Nvm, seems like it is as `@twemoji/parser` but not `twemoji-parser`

**Comment by jdecked** [comment]
Yeah, see the v14.1.0 release notes on this repo for the name change. `twemoji-parser` is probably never getting another publish – at least not from the people who worked on Twemoji (none of us still work at Twitter)

**Comment by ThatOneCalculator** [comment]
Cleared this up in #5
